--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ayaka/Pictures/wallpaper/pwvqya7ifbe91.jpg"

-- Special
background="#12121e"
foreground="#e9cabf"
cursor="#e9cabf"

-- Colors
color0="#12121e"
color1="#B65F48"
color2="#9C6368"
color3="#B68A72"
color4="#D78F75"
color5="#695B8A"
color6="#986984"
color7="#e9cabf"
color8="#a38d85"
color9="#B65F48"
color10="#9C6368"
color11="#B68A72"
color12="#D78F75"
color13="#695B8A"
color14="#986984"
color15="#e9cabf"
